Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:  
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements  
c) Divide every element by 2

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
addition=a+2
print(addition)
multi=a*2
print(multi)
div=a/2
print(div)


[1 2 3 4 5]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:  
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:  
i. x = np.array([1,2,3,4,5,1,2,1,1,1])  
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
arr=np.array([1,2,3,4,5])
rev=arr[::-1]
print(rev)
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
print("Most freq value is ")
mfv=np.bincount(x).argmax()
indices = np.where(x == mfv)[0]
print("Indices of most frequent value:", indices)



[5 4 3 2 1]
[1 2 3 4 5 1 2 1 1 1]
Most freq value is 
Indices of most frequent value: [0 5 7 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:  
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly  
spaced 25 numbers from 10 to 100 using linspace().    Print the dimensions of the array,  
shape,   total elements,   the data type of each element and total number of bytes consumed
by the array.   Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
akansha=np.linspace(10,100,25)
print(akansha)
print(akansha.ndim)
print(akansha.shape)  #no of ele in single dimension
print(akansha.dtype)   #data type of elements
print(akansha.nbytes)    #array takes total 200 bytes in the memory{25*8(float)=200}
transposed_array=akansha.reshape(25,1) #Convert to a column vector
print(transposed_array)
print(akansha.T) #same (25,) coz .T has no effect on 2D Arrays

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.   Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [12]:
ucs420_akansha=np.array([[10,20,30,40],
                         [50,60,70,80],
                         [90,15,20,35]])
print(np.mean(ucs420_akansha))
print(np.median(ucs420_akansha))
print(np.max(ucs420_akansha))
print(np.min(ucs420_akansha))
print(np.unique(ucs420_akansha))
print("reshaped array")
reshaped_ucs420_akansha=ucs420_akansha.reshape(4,3)
print(reshaped_ucs420_akansha)
print("resized array")
resized_ucs420_akansha=np.resize(ucs420_akansha,(2,3))
print(resized_ucs420_akansha)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
reshaped array
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized array
[[10 20 30]
 [40 50 60]]


Gyaan:
1. reshape()  
✅ **Creates a new view of the array without modifying the original.  **

✅ Requires the new shape to be compatible with the original number of elements.
*italicised text*


✅ Raises an error if the total number of elements does not match.


2. resize()  
✅ **Modifies the original array in place (if applied directly)**.

✅ Does not require the total number of elements to match—it adds or removes elements as needed.  

✅ If the new shape has more elements, it fills extra spaces with repeated values (or 0 for uninitialized arrays).